### ISSUE TITLE
Bug: FileNotFoundError while creating .py representation

### ISSUE THREAD

**Issue by max-rasskazov** [sancau/dstrace#5]
pre-commit hook fails to create .py representation of a notebook

Say, we have .dstrace configuration file:
```
confluence_pages:
    dir1/nb2.ipynb:
        code: false
        branch: master
```
Then the following on-commit behavior occurs:
```
Calling DSTrace pre-commit hook

DSTrace pre-commit started.
[NbConvertApp] Converting notebook dir1/nb2.ipynb to script
[NbConvertApp] Writing 68 bytes to dir1/dir1/nb2.ipynb.py
Traceback (most recent call last):
  File "/opt/anaconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 482, in convert_single_notebook
    write_results = self.write_single_notebook(output, resources)
  File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 443, in write_single_notebook
    output, resources, notebook_name=notebook_name)
  File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/writers/files.py", line 126, in write
    with io.open(dest, 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dir1/dir1/nb2.ipynb.py'

DSTrace pre-commit completed.

[master d6adaed] add nb2
 1 file changed, 52 insertions(+)
 create mode 100644 dir1/nb2.ipynb
```

**Comment by sancau** [comment]
That really was a bug. Fixed in version 0.1.6
